version: '3'

networks:
  team-up:

services:
  prisma:
    container_name: prisma-container
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH=trust
    networks:
      - team-up

  team-up:
    container_name: team-up-container
    build: 
      dockerfile: ./Dockerfile
      target: development
      context: .
    environment:
      - DB_URL=postgresql://admin:admin@prisma:5432/team-up?schema=public
      - APP_HOST=localhost:3030
      - TOKEN_SECRET=97c655f1-e7df-4ebf-aa16-68dfb9714530
      - STEAM_SECRET=${STEAM_SECRET}
    networks:
      - team-up
    ports:
      - 3030:3030
    command: bash -c "while !</dev/tcp/prisma/5432; do sleep 1; done; npx prisma generate && npx prisma migrate deploy && npm run dev"

