version: '3'

networks:
  team-up:

services:
  team-up-api:
    container_name: team-up-api
    build: 
      dockerfile: ./Dockerfile
      target: development
      context: .
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
    networks:
      - team-up
    ports:
      - 3030:3030
    command: bash -c "npm run prisma:dev && npm run dev"

